site_name: UI Development

nav:
  - 'index.md'
  - 'docs/tutorial.md'
  - 'Quick Guides':
    - 'docs/configuration.md'
    - 'docs/api.md'
    - 'docs/appstore.md'
    - 'docs/building.md'
    - 'docs/validation.md'
    - 'docs/internationalization.md'
  - 'Advanced Guides':
    - 'docs/monster.md'
    - 'docs/handlebars.md'
    - 'docs/events.md'
    - 'docs/commonControls.md'
    - 'docs/flags.md'
    - 'docs/kazooSdk.md'
    - 'docs/using-postman-as-a-crud.md'
  - 'References':
    - 'appContext':
      - 'docs/appContext/callApi().md'
    - 'monster':
      - 'docs/monster/getTemplate().md'
      - 'docs/monster/isDev().md'
      - 'docs/monster/parallel().md'
      - 'docs/monster/pub().md'
      - 'docs/monster/request().md'
      - 'docs/monster/series().md'
      - 'docs/monster/template().md'
      - 'docs/monster/waterfall().md'
    - 'monster.ui':
      - 'docs/monster-ui/alert().md'
      - 'docs/monster-ui/chosen().md'
      - 'docs/monster-ui/codecSelector().md'
      - 'docs/monster-ui/confirm().md'
      - 'docs/monster-ui/charsRemaining().md'
      - 'docs/monster-ui/countrySelector().md'
      - 'docs/monster-ui/datepicker().md'
      - 'docs/monster-ui/dialog().md'
      - 'docs/monster-ui/disableAutoFill().md'
      - 'docs/monster-ui/generateAppLayout().md'
      - 'docs/monster-ui/getFormData().md'
      - 'docs/monster-ui/getJsoneditor().md'
      - 'docs/monster-ui/getSvgIconTemplate().md'
      - 'docs/monster-ui/highlight().md'
      - 'docs/monster-ui/insertTemplate().md'
      - 'docs/monster-ui/jsoneditor().md'
      - 'docs/monster-ui/keyValueEditor().md'
      - 'docs/monster-ui/keyValueSelector().md'
      - 'docs/monster-ui/loadTab().md'
      - 'docs/monster-ui/mask().md'
      - 'docs/monster-ui/monthpicker().md'
      - 'docs/monster-ui/markdownEditor().md'
      - 'docs/monster-ui/markdownToHtml().md'
      - 'docs/monster-ui/numberPicker().md'
      - 'docs/monster-ui/protectField().md'
      - 'docs/monster-ui/renderJSON().md'
      - 'docs/monster-ui/renderPDF().md'
      - 'docs/monster-ui/showPasswordStrength().md'
      - 'docs/monster-ui/slider().md'
      - 'docs/monster-ui/timepicker().md'
      - 'docs/monster-ui/tooltips().md'
      - 'docs/monster-ui/validate().md'
      - 'docs/monster-ui/wysiwyg().md'
    - 'monster.util':
      - 'docs/monster-util/canAddExternalNumbers().md'
      - 'docs/monster-util/canImpersonate().md'
      - 'docs/monster-util/dateToGregorian().md'
      - 'docs/monster-util/formatMacAddress().md'
      - 'docs/monster-util/formatNumber().md'
      - 'docs/monster-util/formatPhoneNumber().md'
      - 'docs/monster-util/formatPrice().md'
      - 'docs/monster-util/formatVariableToDisplay().md'
      - 'docs/monster-util/getBookkeepers().md'
      - 'docs/monster-util/getBusinessDate().md'
      - 'docs/monster-util/getCapability().md'
      - 'docs/monster-util/getCurrencySymbol().md'
      - 'docs/monster-util/getCurrentTimeZone().md'
      - 'docs/monster-util/getUrlVars().md'
      - 'docs/monster-util/getAuthToken().md'
      - 'docs/monster-util/getFormatPhoneNumber().md'
      - 'docs/monster-util/getNumberFeatures().md'
      - 'docs/monster-util/getUserFullName().md'
      - 'docs/monster-util/gregorianToDate().md'
      - 'docs/monster-util/isAdmin().md'
      - 'docs/monster-util/isLoggedIn().md'
      - 'docs/monster-util/isMasquerading().md'
      - 'docs/monster-util/isReseller().md'
      - 'docs/monster-util/isSuperDuper().md'
      - 'docs/monster-util/isWhitelabeling().md'
      - 'docs/monster-util/parseQueryString().md'
      - 'docs/monster-util/protectSensitivePhoneNumbers().md'
      - 'docs/monster-util/randomString().md'
      - 'docs/monster-util/toFriendlyDate().md'
      - 'docs/monster-util/unixToDate().md'
      - 'docs/monster-util/unformatPhoneNumber().md'
      - 'docs/monster-util/isAuthorizedTopicForCrossSiteMessaging().md'
      - 'dataFlags':
        - 'docs/monster-util/dataFlags.md'
        - 'docs/monster-util/dataFlags/add().md'
        - 'docs/monster-util/dataFlags/destroy().md'
        - 'docs/monster-util/dataFlags/get().md'
    - 'docs/svgIcons.md'
  - 'Contributing':
    - 'docs/branchWorkflow.md'
    - 'docs/codingStandards.md'
    - 'docs/javascriptStyleGuide.md'
    - 'docs/linting.md'
    - 'docs/gitignore.md'
    - 'Documentation templates':
      - 'docs/skeleton/method().md'
      - 'docs/skeleton/object.md'
